### PR TITLE
[Do not merge: Trial] Output tweet data in JSON

### PR DESCRIPTION
**Pull request by jig08**
.. wrt https://github.com/hashkat/hashkat/issues/114

### CODE REVIEW

**Comment by jig08** [comment]
The file `tweets_bank.json` looks like as:
```
{
{"ID:"733
"origID:"733
"time:"99537.5
"origTime"99537.5
};
{"ID:"262
"origID:"262
"time:"99588.4
"origTime"99588.4
};
{"ID:"425
"origID:"425
"time:"99667.2
"origTime"99667.2
};
{"ID:"563
"origID:"563
"time:"99668.2
"origTime"99668.2
};
{"ID:"883
"origID:"883
"time:"99617.8
"origTime"99617.8
};
{"ID:"630
"origID:"630
"time:"99740.8
"origTime"99740.8
};
{"ID:"346
"origID:"346
"time:"99852.2
"origTime"99852.2
};
...
}
```

**Comment by jig08** [comment]
Currently, the `output/tweet_bank.json` file looks something like this: 

```
{
  {
    "ID": 733,
    "origID": 733,
    "time": 99537.5,
    "origTime": 99537.5
  },
  {
    "ID": 262,
    "origID": 262,
    "time": 99588.4,
    "origTime": 99588.4
  },
  {
    "ID": 425,
    "origID": 425,
    "time": 99667.2,
    "origTime": 99667.2
  },
  {
    "ID": 563,
    "origID": 563,
    "time": 99668.2,
    "origTime": 99668.2
  },
  {
    "ID": 883,
    "origID": 883,
    "time": 99617.8,
    "origTime": 99617.8
  },
  {
    "ID": 630,
    "origID": 630,
    "time": 99740.8,
    "origTime": 99740.8
  },
  {
    "ID": 346,
    "origID": 346,
    "time": 99852.2,
    "origTime": 99852.2
  },
  {
    "ID": 212,
    "origID": 212,
    "time": 99862.8,
    "origTime": 99862.8
  },
  {
    "ID": 457,
    "origID": 457,
    "time": 99939.3,
    "origTime": 99939.3
  },
...
}
```

**Comment by jig08** [comment]
@itamblyn 
Here are a few stats:

**Trace (without output in JSON)**
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.93    0.024000        2182        11         5 wait4
  0.07    0.000016           2         9           getegid
  0.00    0.000000           0        11           read
  0.00    0.000000           0         9           open
  0.00    0.000000           0        16         2 close
  0.00    0.000000           0        27        10 stat
  0.00    0.000000           0         8           fstat
  0.00    0.000000           0         5           lseek
  0.00    0.000000           0        14           mmap
  0.00    0.000000           0         8           mprotect
  0.00    0.000000           0         2           munmap
  0.00    0.000000           0        27           brk
  0.00    0.000000           0        19           rt_sigaction
  0.00    0.000000           0        43           rt_sigprocmask
  0.00    0.000000           0         5           rt_sigreturn
  0.00    0.000000           0         1         1 ioctl
  0.00    0.000000           0        13         5 access
  0.00    0.000000           0         2           pipe
  0.00    0.000000           0         1           dup2
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         6           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           uname
  0.00    0.000000           0         3         1 fcntl
  0.00    0.000000           0         2           getdents
  0.00    0.000000           0         2           getrlimit
  0.00    0.000000           0         9           getuid
  0.00    0.000000           0         9           getgid
  0.00    0.000000           0         9           geteuid
  0.00    0.000000           0         1           getppid
  0.00    0.000000           0         1           getpgrp
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           openat
------ ----------- ----------- --------- --------- ----------------
100.00    0.024016                   278        24 total
```
**Trace (with output in JSON)**
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.292000       22462        13         6 wait4
  0.00    0.000000           0        12           read
  0.00    0.000000           0         1           write
  0.00    0.000000           0         9           open
  0.00    0.000000           0        16         2 close
  0.00    0.000000           0        40        17 stat
  0.00    0.000000           0         8           fstat
  0.00    0.000000           0         6           lseek
  0.00    0.000000           0        14           mmap
  0.00    0.000000           0         8           mprotect
  0.00    0.000000           0         2           munmap
  0.00    0.000000           0        27           brk
  0.00    0.000000           0        21           rt_sigaction
  0.00    0.000000           0        51           rt_sigprocmask
  0.00    0.000000           0         6           rt_sigreturn
  0.00    0.000000           0         1         1 ioctl
  0.00    0.000000           0        17         5 access
  0.00    0.000000           0         2           pipe
  0.00    0.000000           0         1           dup2
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         7           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           uname
  0.00    0.000000           0         3         1 fcntl
  0.00    0.000000           0         2           getdents
  0.00    0.000000           0         2           getrlimit
  0.00    0.000000           0        13           getuid
  0.00    0.000000           0        13           getgid
  0.00    0.000000           0        13           geteuid
  0.00    0.000000           0        13           getegid
  0.00    0.000000           0         1           getppid
  0.00    0.000000           0         1           getpgrp
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           openat
------ ----------- ----------- --------- --------- ----------------
100.00    0.292000                   328        32 total
```

**Comment by itamblyn** [comment]
It's important to add a few items to this

- language
- message content


- Isaac

**Comment by jig08** [comment]
Closing for now.

**Pull request closed without merging**
